# Generated by Django 5.2.10 on 2026-02-05 15:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the impact scope.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the impact scope.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of this impact scope.')),
                ('mandatory_notify_email', models.EmailField(blank=True, help_text='Email address that MUST be notified when this scope is impacted (e.g., dpo@company.com).', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this scope is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Impact Scope',
                'verbose_name_plural': 'Impact Scopes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the service.', primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Unique name of the service (used for API lookups).', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the service.')),
                ('runbook_url', models.URLField(blank=True, help_text='Link to the runbook/documentation for incident resolution.')),
                ('repository_url', models.URLField(blank=True, help_text='Link to the source code repository.')),
                ('monitoring_url', models.URLField(blank=True, help_text='Link to the monitoring dashboard (Datadog, Grafana, etc.).')),
                ('criticality', models.CharField(choices=[('TIER_1_CRITICAL', 'Tier 1 - Critical'), ('TIER_2', 'Tier 2 - High'), ('TIER_3', 'Tier 3 - Standard')], db_index=True, default='TIER_3', help_text='Criticality tier of the service.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['criticality', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the incident.', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Short descriptive title of the incident.', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the incident.')),
                ('severity', models.CharField(choices=[('SEV1_CRITICAL', 'SEV1 - Critical'), ('SEV2_HIGH', 'SEV2 - High'), ('SEV3_MEDIUM', 'SEV3 - Medium'), ('SEV4_LOW', 'SEV4 - Low')], db_index=True, default='SEV3_MEDIUM', help_text='Severity level of the incident.', max_length=20)),
                ('status', models.CharField(choices=[('TRIGGERED', 'Triggered'), ('ACKNOWLEDGED', 'Acknowledged'), ('MITIGATED', 'Mitigated'), ('RESOLVED', 'Resolved')], db_index=True, default='TRIGGERED', help_text='Current status in the incident lifecycle.', max_length=20)),
                ('lid_link', models.URLField(blank=True, help_text='Link to the Lead Incident Document (Google Doc).', verbose_name='LID Link')),
                ('war_room_link', models.URLField(blank=True, help_text='Link to the War Room channel (Slack/Discord).')),
                ('war_room_id', models.CharField(blank=True, help_text='Technical ID of the War Room channel (for archiving).', max_length=50)),
                ('detected_at', models.DateTimeField(blank=True, help_text='When the incident was detected by monitoring (from external alert).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the incident was created in IMAS.')),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When a human first acknowledged the incident.', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the incident was marked as resolved.', null=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False, help_text='Whether this incident has been archived.')),
                ('impacted_scopes', models.ManyToManyField(blank=True, help_text='Functional domains impacted (Legal, Security, PR, etc.).', related_name='incidents', to='core.impactscope')),
                ('lead', models.ForeignKey(blank=True, help_text='Person leading the incident response.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_incidents', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(help_text='The primary service affected by this incident.', on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='core.service')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Friendly name for this provider (e.g., 'Slack Prod', 'SMS Astreinte').", max_length=255)),
                ('type', models.CharField(choices=[('SLACK', 'Slack'), ('DISCORD', 'Discord'), ('TEAMS', 'Microsoft Teams'), ('OVH_SMS', 'OVH SMS'), ('SMTP', 'SMTP Email'), ('SCALEWAY_TEM', 'Scaleway Transactional Email'), ('WEBHOOK', 'Generic Webhook'), ('PAGERDUTY', 'PagerDuty'), ('OPSGENIE', 'Opsgenie'), ('NTFY', 'ntfy.sh')], db_index=True, help_text='Type of notification provider.', max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Provider-specific configuration (tokens, webhooks, etc.). Stored as JSON.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this provider is currently active and should be used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Provider',
                'verbose_name_plural': 'Notification Providers',
                'ordering': ['type', 'name'],
                'indexes': [models.Index(fields=['type', 'is_active'], name='core_notifi_type_3453b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, choices=[('ALERTMANAGER', 'Prometheus Alertmanager'), ('DATADOG', 'Datadog'), ('GRAFANA', 'Grafana'), ('CUSTOM', 'Custom Webhook')], help_text='Match specific source, or empty for all', max_length=20)),
                ('alert_name_pattern', models.CharField(blank=True, help_text='Regex pattern to match alert names', max_length=255)),
                ('label_matchers', models.JSONField(default=dict, help_text='Label key-value pairs that must match')),
                ('severity_mapping', models.JSONField(default=dict, help_text='Map alert severity labels to incident severity')),
                ('default_severity', models.CharField(default='SEV3_MEDIUM', help_text='Default severity if no mapping matches', max_length=20)),
                ('auto_create', models.BooleanField(default=True, help_text='Automatically create incidents for matching alerts')),
                ('auto_resolve', models.BooleanField(default=False, help_text='Auto-resolve incident when alert resolves')),
                ('suppress_duplicates_minutes', models.PositiveIntegerField(default=5, help_text='Suppress duplicate alerts within this window')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_service', models.ForeignKey(blank=True, help_text='Service to assign to created incidents', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the team.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name of the team.', max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier for the team.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text="Description of the team's responsibilities.")),
                ('email', models.EmailField(blank=True, help_text='Team distribution list email.', max_length=254)),
                ('slack_channel', models.CharField(blank=True, help_text='Slack channel name (without #) for team notifications.', max_length=100)),
                ('slack_channel_id', models.CharField(blank=True, help_text='Slack channel ID for team notifications (e.g., C0123456789).', max_length=100)),
                ('escalation_timeout_minutes', models.PositiveIntegerField(default=15, help_text='Minutes before escalating to next on-call if no acknowledgment.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_on_call', models.ForeignKey(blank=True, help_text='The person currently on-call for this team.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='on_call_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='owner_team',
            field=models.ForeignKey(help_text='The team responsible for this service.', on_delete=django.db.models.deletion.PROTECT, related_name='services', to='core.team'),
        ),
        migrations.CreateModel(
            name='OnCallSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(db_index=True, help_text='Start of the on-call period.')),
                ('end_time', models.DateTimeField(db_index=True, help_text='End of the on-call period.')),
                ('escalation_level', models.PositiveSmallIntegerField(default=1, help_text='Escalation tier (1=primary, 2=secondary, etc.).')),
                ('notes', models.TextField(blank=True, help_text='Notes about this on-call period (e.g., coverage reason).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User on-call during this period.', on_delete=django.db.models.deletion.CASCADE, related_name='oncall_schedules', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(help_text='Team this schedule belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='oncall_schedules', to='core.team')),
            ],
            options={
                'verbose_name': 'On-Call Schedule',
                'verbose_name_plural': 'On-Call Schedules',
                'ordering': ['start_time', 'escalation_level'],
            },
        ),
        migrations.CreateModel(
            name='AlertFingerprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(db_index=True, help_text='SHA256 hash of alert labels for deduplication', max_length=64, unique=True)),
                ('source', models.CharField(choices=[('ALERTMANAGER', 'Prometheus Alertmanager'), ('DATADOG', 'Datadog'), ('GRAFANA', 'Grafana'), ('CUSTOM', 'Custom Webhook')], default='CUSTOM', max_length=20)),
                ('alert_name', models.CharField(db_index=True, max_length=255)),
                ('labels', models.JSONField(default=dict, help_text='Original alert labels')),
                ('annotations', models.JSONField(default=dict, help_text='Alert annotations')),
                ('status', models.CharField(choices=[('FIRING', 'Firing'), ('RESOLVED', 'Resolved'), ('SUPPRESSED', 'Suppressed')], default='FIRING', max_length=20)),
                ('fire_count', models.PositiveIntegerField(default=1, help_text='Number of times this alert has fired')),
                ('first_fired_at', models.DateTimeField(auto_now_add=True)),
                ('last_fired_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('auto_create_incident', models.BooleanField(default=True, help_text='Whether to auto-create incident for this alert')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_alerts', to='core.incident')),
            ],
            options={
                'ordering': ['-last_fired_at'],
                'indexes': [models.Index(fields=['source', 'alert_name'], name='core_alertf_source_9019ec_idx'), models.Index(fields=['status', 'last_fired_at'], name='core_alertf_status_7c3f66_idx')],
            },
        ),
        migrations.CreateModel(
            name='IncidentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('STATUS_CHANGE', 'Status Change'), ('NOTE', 'Note Added'), ('ALERT_SENT', 'Alert Sent'), ('DOCUMENT_CREATED', 'Document Created'), ('SCOPE_ADDED', 'Impact Scope Added'), ('WAR_ROOM_CREATED', 'War Room Created'), ('ESCALATION', 'Escalation'), ('REMINDER', 'Reminder Sent'), ('ARCHIVED', 'Archived')], db_index=True, help_text='Type of event.', max_length=30)),
                ('message', models.TextField(help_text='Description of what happened.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this event occurred.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who triggered this event (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_events', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(help_text='The incident this event belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.incident')),
            ],
            options={
                'verbose_name': 'Incident Event',
                'verbose_name_plural': 'Incident Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['incident', '-timestamp'], name='core_incide_inciden_3d44ea_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', 'severity'], name='core_incide_status_a6cf12_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['service', 'status'], name='core_incide_service_09ca29_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['-created_at'], name='core_incide_created_e03684_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['criticality', 'name'], name='core_servic_critica_09d210_idx'),
        ),
        migrations.AddIndex(
            model_name='oncallschedule',
            index=models.Index(fields=['team', 'start_time', 'end_time'], name='core_oncall_team_id_95ee72_idx'),
        ),
        migrations.AddIndex(
            model_name='oncallschedule',
            index=models.Index(fields=['user', 'start_time'], name='core_oncall_user_id_6016f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='oncallschedule',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='oncall_end_after_start'),
        ),
    ]
