# Generated by Django 5.2.10 on 2026-02-05 16:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('LOGIN_FAILED', 'Failed Login Attempt'), ('TOKEN_CREATED', 'API Token Created'), ('TOKEN_REVOKED', 'API Token Revoked'), ('INCIDENT_CREATED', 'Incident Created'), ('INCIDENT_VIEWED', 'Incident Viewed'), ('INCIDENT_UPDATED', 'Incident Updated'), ('INCIDENT_ACKNOWLEDGED', 'Incident Acknowledged'), ('INCIDENT_RESOLVED', 'Incident Resolved'), ('INCIDENT_ESCALATED', 'Incident Escalated'), ('TEAM_CREATED', 'Team Created'), ('TEAM_UPDATED', 'Team Updated'), ('SERVICE_CREATED', 'Service Created'), ('SERVICE_UPDATED', 'Service Updated'), ('API_REQUEST', 'API Request'), ('API_ERROR', 'API Error'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('PERMISSION_CHANGED', 'Permission Changed'), ('NOTIFICATION_SENT', 'Notification Sent'), ('NOTIFICATION_FAILED', 'Notification Failed')], db_index=True, max_length=50)),
                ('resource_type', models.CharField(blank=True, max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='core_auditl_user_id_2a1528_idx'), models.Index(fields=['action', '-timestamp'], name='core_auditl_action_f07419_idx'), models.Index(fields=['resource_type', 'resource_id'], name='core_auditl_resourc_a674ad_idx'), models.Index(fields=['-timestamp'], name='core_auditl_timesta_189a84_idx')],
            },
        ),
    ]
