# Generated by Django 5.2.10 on 2026-02-05 16:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Tag name (e.g., 'database', 'networking', 'customer-impacting').", max_length=100, unique=True)),
                ('color', models.CharField(default='#6B7280', help_text="Hex color for display (e.g., '#FF0000').", max_length=7)),
                ('description', models.TextField(blank=True, help_text='Description of when to use this tag.')),
                ('is_active', models.BooleanField(default=True)),
                ('auto_apply_pattern', models.CharField(blank=True, help_text='Regex pattern to auto-apply this tag.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EscalationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the escalation policy.', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('severity_filter', models.CharField(blank=True, help_text='Only apply to this severity level (optional).', max_length=20)),
                ('initial_delay_minutes', models.PositiveIntegerField(default=15, help_text='Minutes before first escalation if not acknowledged.')),
                ('repeat_interval_minutes', models.PositiveIntegerField(default=30, help_text='Minutes between repeated escalations.')),
                ('max_escalations', models.PositiveIntegerField(default=3, help_text='Maximum number of escalation attempts.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(help_text='Team this policy applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='escalation_policies', to='core.team')),
            ],
            options={
                'verbose_name': 'Escalation Policy',
                'verbose_name_plural': 'Escalation Policies',
                'ordering': ['team', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EscalationStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(help_text='Order in the escalation chain.')),
                ('notify_type', models.CharField(choices=[('user', 'Specific User'), ('oncall', 'Current On-Call'), ('team', 'Entire Team'), ('manager', 'Team Manager')], default='oncall', max_length=20)),
                ('delay_minutes', models.PositiveIntegerField(default=0, help_text='Additional delay before this step (added to policy delay).')),
                ('notification_channels', models.JSONField(default=list, help_text="Channels to use: ['slack', 'email', 'sms', 'phone']")),
                ('notify_user', models.ForeignKey(blank=True, help_text="User to notify (if notify_type is 'user').", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.escalationpolicy')),
            ],
            options={
                'verbose_name': 'Escalation Step',
                'verbose_name_plural': 'Escalation Steps',
                'ordering': ['policy', 'order'],
                'unique_together': {('policy', 'order')},
            },
        ),
        migrations.CreateModel(
            name='IncidentComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_type', models.CharField(choices=[('manual', 'Manual Comment'), ('status', 'Status Change'), ('auto', 'Automated Update'), ('escalation', 'Escalation'), ('resolution', 'Resolution Note')], default='manual', max_length=20)),
                ('content', models.TextField(help_text='The comment content (supports Markdown).')),
                ('is_internal', models.BooleanField(default=False, help_text='Internal comments are not shown in public status pages.')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned comments appear at the top.')),
                ('source_system', models.CharField(blank=True, help_text="Source system for automated comments (e.g., 'slack', 'pagerduty').", max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for the comment.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_comments', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.incident')),
            ],
            options={
                'verbose_name': 'Incident Comment',
                'verbose_name_plural': 'Incident Comments',
                'ordering': ['-is_pinned', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentEscalation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('escalation_number', models.PositiveIntegerField(help_text='Which escalation attempt this is (1, 2, 3, ...).')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('notified', 'Notified'), ('acknowledged', 'Acknowledged'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('channels_used', models.JSONField(default=list, help_text='Notification channels that were used.')),
                ('error_message', models.TextField(blank=True, help_text='Error message if escalation failed.')),
                ('scheduled_at', models.DateTimeField(help_text='When this escalation is/was scheduled.')),
                ('executed_at', models.DateTimeField(blank=True, help_text='When this escalation was actually executed.', null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When this escalation was acknowledged.', null=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='core.incident')),
                ('notified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_escalations', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.escalationpolicy')),
                ('step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.escalationstep')),
            ],
            options={
                'verbose_name': 'Incident Escalation',
                'verbose_name_plural': 'Incident Escalations',
                'ordering': ['incident', 'escalation_number'],
            },
        ),
        migrations.CreateModel(
            name='Runbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the runbook.', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of when to use this runbook.')),
                ('alert_pattern', models.CharField(blank=True, help_text="Regex pattern to match alert names (e.g., 'HighCPU.*').", max_length=255)),
                ('severity_filter', models.CharField(blank=True, help_text='Only apply to this severity level (optional).', max_length=20)),
                ('quick_actions', models.JSONField(blank=True, default=list, help_text='List of quick action buttons with commands.')),
                ('external_docs', models.JSONField(blank=True, default=list, help_text='List of external documentation links.')),
                ('version', models.CharField(default='1.0', help_text='Version of this runbook.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this runbook is active.')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When this runbook was last used.', null=True)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this runbook has been used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_runbooks', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, help_text='Service this runbook applies to (optional).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runbooks', to='core.service')),
            ],
            options={
                'verbose_name': 'Runbook',
                'verbose_name_plural': 'Runbooks',
                'ordering': ['service', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RunbookStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(help_text='Order of this step in the runbook.')),
                ('title', models.CharField(help_text='Short title for this step.', max_length=255)),
                ('description', models.TextField(help_text='Detailed instructions for this step.')),
                ('command', models.TextField(blank=True, help_text='Optional command to execute (for reference).')),
                ('expected_duration_minutes', models.PositiveIntegerField(default=5, help_text='Expected time to complete this step.')),
                ('is_critical', models.BooleanField(default=False, help_text='Whether this step is critical and must not be skipped.')),
                ('requires_confirmation', models.BooleanField(default=False, help_text='Whether this step requires explicit confirmation.')),
                ('rollback_instructions', models.TextField(blank=True, help_text='Instructions to rollback this step if needed.')),
                ('runbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.runbook')),
            ],
            options={
                'verbose_name': 'Runbook Step',
                'verbose_name_plural': 'Runbook Steps',
                'ordering': ['runbook', 'order'],
                'unique_together': {('runbook', 'order')},
            },
        ),
        migrations.CreateModel(
            name='IncidentTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_auto_applied', models.BooleanField(default=False, help_text='Whether this tag was auto-applied.')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_tags', to='core.incident')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_tags', to='core.tag')),
            ],
            options={
                'verbose_name': 'Incident Tag',
                'verbose_name_plural': 'Incident Tags',
                'unique_together': {('incident', 'tag')},
            },
        ),
    ]
